name: Check pull request description checkbox
description: 'Validate if a specific checkbox in a pull request description is checked or not.'

branding:
  icon: 'award'
  color: 'green'

on:
  pull_request:
    types: [opened, synchronize, edited]

# Here you must declare the name of the checkbox you want to verify
# remember the name of your checkbox must be in lowercase
env:
  checkbox: "integration test (mandatory)"

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          UNCHECKED="\[ \] $checkbox"
          MARKED="\[x\] $checkbox"
           if echo ${BODY,,} | grep -q "$MARKED"; then
            echo "Checkbox is checked"
            exit 0
          elif echo ${BODY,,} | grep -q "$UNCHECKED"; then
            echo "Checkbox is not checked"
            exit 1
          else
            echo "Checkbox not found in pull request description"
            exit 1
          fi