name: Check README
description: 'Check if integration test checkbox has been marked'


branding:
  icon: 'award'
  color: 'green'

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
      - - name: Print PR Template
          run: |
            README_FILE="./pull_request_template.md"
            cat "$README_FILE"
            echo "pr template"

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Check README
        run: |
          CHECKBOX="[ ]  Integration test (Mandatory)"
          MARKED="[x]  Integration test (Mandatory)"
          README_FILE="./pull_request_template.md"
          
          if grep -q "$MARKED" "$README_FILE"; then
            echo "Integration test run"
          elif grep -q "$CHECKBOX" "$README_FILE"; then
            echo "Integration test not run"
          else
            echo "Checkbox not found in README"
          fi