name: Check README
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check README
        run: |
          CHECKBOX="\[ \]  Integration test (Mandatory)"
          MARKED="\[x\]  Integration test (Mandatory)"
          README_FILE="${{ github.event.pull_request.body }}"
          
          if echo "$README_FILE" | grep -q "$MARKED"; then
            echo "Integration test run"
            exit 0
          elif echo "$README_FILE" | grep -q "$CHECKBOX"; then
            echo "Integration test not run"
            exit 1
          else
            echo "Checkbox not found in README"
            exit 1
          fi