name: Check pull request description checkbox
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description
        run: |
          CHECKBOX="[ ]  Integration test (Mandatory)"
          MARKED="[x]  Integration test (Mandatory)"
          README_FILE="${{ github.event.pull_request.body }}"
          echo "pull request descirption"
          echo "$README_FILE"
          grep -v '`' $(cat "$README_FILE")
          echo "ya en el file"

