name: Check pull request description checkbox
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description
        run: |
          CHECKBOX="[ ]  Integration test (Mandatory)"
          MARKED="[x]  Integration test (Mandatory)"
          README_FILE="${{ github.event.pull_request.body }}"
          if echo $(cat "$README_FILE") | grep -Fq "$MARKED"; then
            echo "Integration test run"
            exit 0
          elif echo $(cat "$README_FILE") | grep -Fq "$CHECKBOX"; then
            echo "Integration test not run"
            exit 1
          else
            echo "Checkbox not found in README"
          fi
