name: Check pull request description checkbox
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          CHECKBOX="[ ]  Integration test (Mandatory)"
          MARKED="[x]  Integration test (Mandatory)"
                    echo "pull request descirption"

          README_FILE= awk '{gsub(/`/, ""); print}' $BODY
          echo "pull request descirption"
          echo "ya en el file"

