name: Check pull request description checkbox
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          UNCHECKED="[ ] integration test"
          MARKED="[x] integration test"
          echo ${BODY,,}
           if echo ${BODY,,} | grep -q "$MARKED"; then
            echo "Checkbox is checked"
            exit 0
          elif echo ${BODY,,} | grep -q "$UNCHECKED"; then
            echo "Checkbox is not checked"
            exit 1
          else
            echo "Checkbox not found in pull request description"
            exit 1
          fi

