name: Check pull request description checkbox
on:
  pull_request:
    types: [opened, synchronize, edited]

# Here you must declare the name of the checkbox you want to verify
env:
  checkbox: " Integration test (Mandatory)"

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description
        run: |
          CHECKED="\[x\]  $checkbox"
          UNCHECKED="\[ \]  $checkbox"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          echo $CHECKED
          echo $UNCHECKED
          if echo "$PR_DESCRIPTION" | grep -q "$CHECKED"; then
            echo "Checkbox is checked"
            exit 0
          elif echo "$PR_DESCRIPTION" | grep -q "$UNCHECKED"; then
            echo "Checkbox is not checked"
            exit 1
          else
            echo "Checkbox not found in pull request description"
            exit 1
          fi
