name: Check README
description: 'Check if integration test checkbox has been marked'

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request description
        run: |
          CHECKBOX="[ ]  Integration test (Mandatory)"
          MARKED="[x]  Integration test (Mandatory)"
          README_FILE="${{ github.event.pull_request.body }}"
          echo "reading body"
          echo $(cat $README_FILE)
          if echo $(cat $README_FILE) | grep -Fq "$MARKED"; then
            echo "Integration test run"
            exit 0
          elif echo $(cat "$README_FILE") | grep -Fq "$CHECKBOX"; then
            echo "Integration test not run"
            exit 1
          else
            echo "Checkbox not found in README"
            exit 1
          fi